# -------------------------------------------------------------------------
# Override some Makefile defaults to match DOS environment:

RM=del
OOBJ=-o
EOBJ=-e
TARG_OOBJ=$(OOBJ)
TARG_EOBJ=$(EOBJ)
CURRDIR=.\\
LIBM=
CHECK_TARG_CC=

# -------------------------------------------------------------------------
# choose your compiler (must be ANSI-compliant!) and linker command, plus
# any additionally needed flags

OBJDIR =
CC = bcc
CFLAGS =-WX -w-stu -ml -Oe -k- -Z -d -dc
HOST_OBJEXTENSION = .obj
LD = bcc -WX
LDFLAGS =
HOST_EXEXTENSION = .exe

# no cross build

TARG_OBJDIR = $(OBJDIR)
TARG_CC = $(CC)
TARG_CFLAGS = $(CFLAGS)
TARG_OBJEXTENSION = $(HOST_OBJEXTENSION)
TARG_LD = $(LD)
TARG_LDFLAGS = $(LDFLAGS)
TARG_EXEXTENSION = $(HOST_EXEXTENSION)

# -------------------------------------------------------------------------
# directory where binaries, includes, and manpages should go during
# installation:

INSTROOT:=c:\as
